# coding: utf-8

"""
    Data Analytics API

    Data Analytics API specification developed in-house at xFlow Research.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cdr import CDR  # noqa: E501
from swagger_client.rest import ApiException


class TestCDR(unittest.TestCase):
    """CDR unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCDR(self):
        """Test CDR"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cdr.CDR()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
