# coding: utf-8

"""
    Data Analytics API

    Data Analytics API specification developed in-house at xFlow Research.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_calls_cdr_id_get(self):
        """Test case for calls_cdr_id_get

        Return a list of Call Data Records (CDRs).  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
