openapi: 3.0.0
info:
  title: Data Analytics API
  description: Data Analytics API specification developed in-house at xFlow Research.
  version: 0.4.0

servers:
  - url: /v1alpha4
    description: Version 1 alpha version 4 for the Data Analytics API.

paths:
  /calls:
    get:
      summary: Return a list of Call Data Records (CDRs).
      description: This endpoint will be used to retrieve CDR list using
        'offset' and 'size' parameters. The CDR list will always have less
        than or equal to 'size' number of entries.
      parameters:
        - name: offset
          in: query
          required: true
          description: The CDR-ID offset to use for retrieving CDRs.
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: size
          in: query
          required: true
          description: The maximum number of CDRs to retrieve.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A valid list of Call Data Records from the Database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CDRList'
  /calls/{cdrId}:
    get:
      summary: Return a list of Call Data Records (CDRs).
      description: This endpoint is currently being used for getting the CDR for
        a specific call, by providing the CDR-ID as '/calls/{cdr-id}'.
      parameters:
        - name: cdrId
          in: path
          required: true
          description: The CDR-ID of the call for which to retrieve the CDR.
          schema:
            type: integer
            # The DB schema lists ID in CDR table as BIGINT which is 64 bits.
            format: int64
            minimum: 1
      responses:
        '200':
          description: A valid Call Data Record entry from the Database.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CDR'
  /pcap:
    get:
      summary: Return a PCAP of a call
      description: This endpoint returns the Packet Capture (PCAP) of a call
        identified by the given CDR-ID. It contains both SIP and RTP by
        default. It accepts a flag 'disable_rtp' to provide only SIP in the
        PCAP.
      parameters:
        - name: cdrId
          in: query
          required: true
          description: The CDR-ID of the call for which to retrieve the PCAP.
          schema:
            type: integer
            minimum: 1
        - name: disable_rtp
          in: query
          required: false
          description: The flag to disable RTP component in the PCAP of the
            call.
          schema:
            type: integer
            minimum: 1
            maximum: 1
      responses:
        '200':
          description: A call was found in the database successfully and PCAP
            is being returned.
          headers:
            Content-Disposition:
              description: The header to provide the filename of the PCAP as
                the Call-ID of the Call.
              schema:
                type: string
          content:
            application/octet-stream:
              schema:
                type: object
                format: binary
  /audio/{cdrId}:
    get:
      summary: Return the Audio file of a call identified with cdrId
      description: This API endpoint identifies a call with the given 
        cdrId and then provides the audio file of the decoded audio of
        the VoIP call in WAV format.
      parameters:
        - name: cdrId
          in: path
          required: true
          description: CDR-ID of the call to identify it.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A call was identified with the given CDR-ID and
            the decoded payload of the call is being returned as WAV audio.
          headers:
            Content-Disposition:
              description: The filename of the audio file that is being returned.
              schema:
                type: string
          content:
            audio/x-wav:
              schema:
                type: object
                format: binary
  /audio/{callId}:
    get:
      summary: Return the Audio file of a call identified with callId
      description: This API endpoint identifies a call with the given
        callId and then provides the audio file of the decoded audio of
        the VoIP call in WAV format.
      parameters:
        - name: callId
          in: path
          required: true
          description: Call-ID of the call to identify it.
          schema:
            type: string
      responses:
        '200':
          description: A call was identified with the given Call-ID and
            the decoded payload of the call is being returned as WAV audio.
          headers:
            Content-Disposition:
              description: The filename of the audio file that is being returned.
              schema:
                type: string
          content:
            audio/x-wav:
              schema:
                type: object
                format: binary

components:
  schemas:
  # A wrapper object with only one property 'cdr' as per API guide.
    CDRList:
      type: object
      properties:
        cdr:
          description: A list of CDR entries.
          type: array
          items:
            $ref: '#/components/schemas/CDR'

  # The schema of the Call Data Record that will be retrieved - this is in
  # according to the API Guide document.
    CDR:
      type: object
      properties:
        cdrId:
          description: The CDR ID of the retrieved CDR.
          type: string
          example: '40122'
        caller:
          description: The MSISDN of the Caller from SIP 'From' header
          type: string
          example: '4179383431512'
        called:
          description: The MSISDN of the Callee from SIP 'To' header
          type: string
          example: '4179383431512'
        calldate:
          description: Start date and time of call in ISO 8601 format, with the
            configured timezone. It will be the time since the first SIP INVITE
            packet.
          type: string
          example: 2019-01-28T15:19:45+0400
        callend:
          description: End date and time of call in ISO 8601 format, with the
            configured timezone. It will be the time of the last received packet.
          type: string
          example: 2019-01-28T15:20:00+0400
        callId:
          description: Call ID of the CDR in the database.
          type: string
          example: sshcbKlTL@10.231.96.147
        duration:
          description: Total duration of the call. (The interval between
            'callend' - 'calldate' as number of seconds)
          type: string
          example: '14'
        connect_duration:
          description: Number of seconds the call was connected (seconds between
            SIP 200 OK and callend). Value will be 'null' if no SIP 200 OK packet
            is sent by the callee. Value will be '0' if SIP 200 OK is sent by the
            callee but no RTP packets were exchanged.
          type: string
          example: null
        sipcallerip:
          description: IP address of the SIP caller.
          type: string
          example: '10.238.249.55'
        sipcallerport:
          description: Port number of the SIP caller.
          type: string
          example: '44410'
        sipcalledip:
          description: IP address of the SIP callee.
          type: string
          example: '10.238.235.248'
        sipcalledport:
          description: Port number of the SIP callee.
          type: string
          example: '5060'
        codec_a:
          description: CODEC of the caller for RTP stream.
          type: string
          example: AMR-WB
        codec_b:
          description: CODEC of the callee for RTP stream.
          type: string
          example: AMR-WB
        a_last_rtp_from_end:
          description: Last RTP packet arrival time for caller (in seconds) before
            the call was closed.
          type: string
          example: '55'
        b_last_rtp_from_end:
          description: Last RTP packet arrival time for callee (in seconds) before
            the call was closed.
          type: string
          example: '10'
        Cell_ID_Caller:
          description: Cell ID of the caller.
          type: string
          example: 42402A4800392F08
        Cell_ID_Called:
          description: Cell ID of the callee.
          type: string
          example: 42402a49403aa802
        IMSI-Contact:
          description: IMSI of the caller/callee from the Contact URI User Part
            parameter.
          type: string
          example: XXXXXXXXXXXXXXX
        IMSI-Request:
          description: IMSI of the caller/callee from the Request URI User Part
            parameter.
          type: string
          example: XXXXXXXXXXXXXXX
        Session-ID:
          description: Session-ID of the call
          type: string
          example: XXXXXXXXXXXXXXX