# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cdr import CDR  # noqa: F401,E501
from swagger_server import util


class CDRList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cdr: List[CDR]=None):  # noqa: E501
        """CDRList - a model defined in Swagger

        :param cdr: The cdr of this CDRList.  # noqa: E501
        :type cdr: List[CDR]
        """
        self.swagger_types = {
            'cdr': List[CDR]
        }

        self.attribute_map = {
            'cdr': 'cdr'
        }
        self._cdr = cdr

    @classmethod
    def from_dict(cls, dikt) -> 'CDRList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CDRList of this CDRList.  # noqa: E501
        :rtype: CDRList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cdr(self) -> List[CDR]:
        """Gets the cdr of this CDRList.

        A list of CDR entries.  # noqa: E501

        :return: The cdr of this CDRList.
        :rtype: List[CDR]
        """
        return self._cdr

    @cdr.setter
    def cdr(self, cdr: List[CDR]):
        """Sets the cdr of this CDRList.

        A list of CDR entries.  # noqa: E501

        :param cdr: The cdr of this CDRList.
        :type cdr: List[CDR]
        """

        self._cdr = cdr
