# coding: utf-8

# flake8: noqa
"""
    Data Analytics API

    Data Analytics API specification developed in-house at xFlow Research.  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.cdr import CDR
